### ISSUE TITLE
How does this tool work wat does it do

### ISSUE THREAD

**Issue by AndrianiP** [lassevk/WarframeTools#1]
What does this tool do?

**Comment by lassevk** [comment]
I'm sorry but this tool isn't mean to be for anyone but myself.

But, since you ask, here's what I intended for the tool to do:

* Maintain a list of relics that I have, which means I somehow need to tell the tool which relics I have, any relics I've gained and any I have used
* List relics that would give me a particular item
* List items I could give from a particular relic
* List relics, ordered by the average ducat value I would gain from using them

Right now there is no way to easily inform the program of this list of relics, other than to provide a specific file of relic information. (let me know if you really want to go down this path and I'll provide the necessary instruction)

I would probably add additional features as I go along but it's not a project I'm prioritizing right now. The project is reliant on a private nuget repository that I maintain, and if you absolutely want to look at the tool and its use you could add http://teamcity.vkarlsen.no/guestAuth/app/nuget/feed/Lvk/default/v3/index.json as a private nuget repository, this would allow you to restore the packages needed for the Warframe Tools projects. The nuget packages are from my other github project - https://github.com/lassevk/LVK - so in theory you can compile everything from public sources (it'll be a bit of work though.)

**Comment by lassevk** [comment]
I'll be closing this issue for the time being, but if you want to use the code for anything, let me know, either by replying here (I'm assuming this will re-open this issue, but if not ...)= or by opening another issue or by simply sending me an email, to lasse@vkarlsen.no.
